# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

language: python
python:
        - 2.7
        - 3.6
dist: xenial
addons:
  apt:
    packages:
      - openjdk-8-jre-headless
      - ant
matrix:
  include:
    - python: 3.7
      sudo: true
cache: pip

before_install:
  # Note: Change next line once support scripts are fixed
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git -b rat support
  - support/rat.sh download
### Don't need this at the moment
#   # Bring pip up to date
#   - pip install --upgrade pip setuptools wheel
#   - pip install --only-binary=numpy,scipy numpy scipy

install:
  - python ./setup.py install
  - pip install -r requirements-test.txt
  - pip install python-coveralls 'coverage>=4.4'

script:
  - py.test . --cov spinn_utilities
  # Code quality check
  - flake8 spinn_utilities unittests
  - support/rat.sh run -E .ratexclude -d .
  - cd doc/source
  - sphinx-build -W -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -W -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -W -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
